import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>hosPETal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>hosPETal</h1>
        <p>동물병원 예약 서비스</p>
      </main>
    </>
  )
}
